### ISSUE TITLE
Questionnaire with `:status: maintennace` does not work properly

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus-rst-tools#110]
If a questionnaire status is set to `maintenance`. The exercise is listed in the table of content and it allows the students to submit answers as normal.

**MWE**
```rst
.. questionnaire:: status_maintenance
  :title: Question with a ``maintenance`` status. The questionnaire is hidden along with the previous submissions.
  :submissions: 4
  :category: Status
  :status: maintenance

  .. pick-one:: 10
    :required:

    What is 1+1?

    a. 1
    *b. 2
    c. 3

    !b § Count again!
    b § That is correct!
    c § Too much
```

**Listed in the table of content**
![image](https://user-images.githubusercontent.com/10437475/101740928-1f716380-3ad2-11eb-9c39-35035d16bea3.png)

**Allow student submission**
![image](https://user-images.githubusercontent.com/10437475/101740843-05378580-3ad2-11eb-8f34-f06077c62581.png)

**Actually,**  the questionnaire is only in a maintenance mode when the user accesses the questionnaire directly.
![image](https://user-images.githubusercontent.com/10437475/101740730-e33e0300-3ad1-11eb-99a2-207662bf62d1.png)

**Comment by Mankro** [comment]
I think the idea with the maintenance mode has been
* to show the exercise in the table of contents as normal,
* to hide the exercise description from students, and 
* to prevent any new submissions to the exercise.

If exercises in chapters do not respect the maintenance status, then that should be fixed.

Maintenance mode is not used much. One of the problems is that teachers would often want to show  the exercise, but prevent new submissions and show a warning that submissions will be enabled soon once the grader is fixed. Currently, the exercise description is always hidden in the maintenance status. I wouldn't change that now. There are needs for both hiding and showing the exercise description, but this has very low priority.
