### ISSUE TITLE
FutureWarning in toc_config.py

### ISSUE THREAD

**Issue by jykesaviaGNH** [apluslms/a-plus-rst-tools#116]
Should be taken into account if/when supported sphinx/docutils are updated.

```
/compile/a-plus-rst-tools/toc_config.py:49: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  return tocs and tocs[0].get('rawcaption') == 'Select language'
/compile/a-plus-rst-tools/toc_config.py:202: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  return titles[0].astext() if titles else u'Unnamed'
```

https://github.com/apluslms/a-plus-rst-tools/blob/135b5c97dc948ffbc87274777ab209fa0e057a33/toc_config.py#L49

https://github.com/apluslms/a-plus-rst-tools/blob/135b5c97dc948ffbc87274777ab209fa0e057a33/toc_config.py#L202

**Comment by Mankro** [comment]
We are planning to upgrade Sphinx in the spring 2021 because we are otherwise too dependent on outdated Python versions (v3.5). A-plus-rst-tools will require many changes in order to support the new Sphinx versions.
