### ISSUE TITLE
Index joiner crash in trilingual courses

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus-rst-tools#118]
a-plus-rst-tools index joiner may crash in trilingual courses if languages refer to the same RST files, e.g., Swedish toctree refers to some `_en.rst` files.

Trilingual courses are important in exams: Finnish, Swedish, English.

Test here: https://github.com/apluslms/test-course/tree/trilingual

**Comment by skulonen** [comment]
@Mankro Trilingual courses no longer crash the index joiner, thanks to apluslms/a-plus-rst-tools#125.

The first link on the Swedish `links1/chapter2` page refers to `chapter1_en` in the RST file, but in the web UI, it links to `chapter1` of the current language (Swedish). Is this working correctly, or should it append the `hl=en` query parameter to the URL?

**Comment by Mankro** [comment]
> @Mankro Trilingual courses no longer crash the index joiner, thanks to #125.
> 
> The first link on the Swedish `links1/chapter2` page refers to `chapter1_en` in the RST file, but in the web UI, it links to `chapter1` of the current language (Swedish). Is this working correctly, or should it append the `hl=en` query parameter to the URL?

It looks like the Swedish chapter https://github.com/apluslms/test-course/blob/trilingual/links1/chapter2_sv.rst has a link to `chapter1_en` by accident and it was supposed to be `chapter1_sv`. Note that a-plus-rst-tools can automatically add the missing language suffixes, but the test course also tests the case when the language suffix is given: 
https://github.com/apluslms/a-plus-rst-tools/blob/10ef219e65bf8957f60aa5f3cf2ae28fb7103032/toc_config.py#L56

A-plus-rst-tools do not know of the A+ `hl=en` language URL parameters. It would be a new feature if it was possible to link from a chapter to another language version. Sphinx can not directly support that. Currently, a-plus-rst-tools contains hacky URL manipulations in https://github.com/apluslms/a-plus-rst-tools/blob/master/lib/html_tools.py that take care of a few A+-specific URL issues that Sphinx can't do.

**Comment by skulonen** [comment]
@Mankro I think we can also close this now that apluslms/mooc-grader#96 is fixed and the index joiner no longer crashes.
