### ISSUE TITLE
Multilingual support for category names

### ISSUE THREAD

**Issue by piehei** [apluslms/a-plus-rst-tools#26]
At the moment it is not possible to configure multilingual category names in a-plus-rst-tools (to the best of my knowledge at least!).

So this doens't work:

exercise_fi.rst ... submit ... :category: viikko
exercise_en.rst ... submit ... :category: weekly

It emits something like:

WARNING: Missing 1 fields at categories.viikko in en: viikko
WARNING: Surplus 1 fields at categories.weekly in en: weekly
WARNING: Missing 1 fields at categories.viikko.name in en: name
WARNING: Unequal field not accepted in en: modules.1.12.1.category
WARNING: Unequal field not accepted in en: round01_05_eka_palautus_eka_palautus.category

**Comment by Mankro** [comment]
You can define this in conf.py:

```
category_names = {
    'chapter': {
        'fi': 'Luku',
        'en': 'Chapter',
    },
    'submit': {
        'fi': 'Tehtävä',
        'en': 'Exercise',
    },
    'feedback': {
        'fi': 'Palaute',
        'en': 'Feedback',
    },
}
```

Submit directive uses the category "submit" by default. You could also define some other category with the category option. All language versions must use the same key word in the category option of the submit RST directive.
