### ISSUE TITLE
Group setting for questionnaires and submits

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus-rst-tools#70]
The RST `questionnaire` directive should have options `max-group-size` and `min-group-size` so that the group size settings can be configured for each questionnaire separately instead of only using the course-wide default settings from `conf.py`. 

In addition, the group size options shall be added to the `submit` directive too. Those exercises can use settings from the linked config.yaml file, but it is nice to have basic settings in the RST directive options too. The RST options are prioritized if the same settings are defined in two places.

Some advice:

* `option_spec` dict in `directives/questionnaire.py`
* https://github.com/Aalto-LeTech/a-plus-rst-tools/blob/d2dd81fa98a5e7098180de3cc7f8e0c6f134e6df/directives/questionnaire.py#L116 sets the configurations to the output YAML file.
* the group size option could be used with feedback questionnaires too. Currently, the code forces feedback questionnaires to one-person groups.

**Comment by raphendyr** [comment]
Two things. First. I think most of the directives should use inheritance to include common options, like group sizes. Second, MOOC-Jutut doesn't support groups, but other feedback backends of course.

**Comment by oseppala** [comment]
Correct me if Im wrong, but isn't this just adding these to lines in the option spec:
'max_group_size': directives.nonnegative_int,
'min_group_size': directives.nonnegative_int,

I can set the value through a corresponding YAML. Only the option spec is missing.

**Comment by oseppala** [comment]
(I managed to disable an exercise today by using the max_group_size variable in RST)

**Comment by Mankro** [comment]
Yes, this would be easy to add to the a-plus-rst-tools code, but it hasn't been done yet.

**Comment by Mankro** [comment]
> max_group_size

RST directive options prefer the spelling `max-group-size`.

**Comment by oseppala** [comment]
True, thats the variable name in python. Then its edits on lines 116 and 117 in the same style as 115.

**Comment by oseppala** [comment]
That should be a 15 minutes task

**Comment by oseppala** [comment]
And it's not just questionnaires!

**Comment by Mankro** [comment]
@oseppala fixed in the version v1.5.2
https://github.com/apluslms/a-plus-rst-tools/releases/tag/v1.5.2
